server:
  port: 3000

spring:
  datasource: # 数据源配置，用于数据库连接
    username: Rain
    password: 1120Rain
    driver-class-name: com.mysql.cj.jdbc.Driver # 指定数据库驱动的完全限定名，这里是MySQL的驱动
    url: jdbc:mysql://203.195.210.183:3306/code_campus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false # 数据库的URL，包括数据库服务器的地址和端口，以及数据库名
    type: com.alibaba.druid.pool.DruidDataSource # 指定数据源的类型，这里是阿里巴巴的Druid连接池
    druid: # Druid连接池的特定配置
      initial-size: 20 # 连接池的初始大小
      min-idle: 20 # 连接池中最小的空闲连接数
      max-active: 100 # 连接池中最大的活动连接数
      max-wait: 6000 # 连接池等待连接的最大时间，单位为毫秒
      stat-view-servlet: # 用于监控Druid连接池状态的配置
        enabled: true # 开启状态监控
        url-pattern: /druid/* # 监控页面的URL模式
        login-username: admin # 监控页面的登录用户名
        login-password: 123456 # 监控页面的登录密码
        filter: # 过滤器配置
          stat: # 统计过滤器
            enabled: true # 开启统计功能
            slow-sql-millis: 2000 # 慢SQL的阈值，超过这个时间的SQL被认为是慢SQL
            log-slow-sql: true # 是否记录慢SQL
          wall: # 执行SQL的防火墙
            enabled: true # 开启防火墙功能
          config: # 配置过滤器
            enabled: true # 开启配置功能
      connection-properties: "config.decrypt=true;config.decrypt.key=${publicKey}"
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIgBIegoVW6lsRaTRO7fGiHbGDskYKi2woBIK8KVV13NoOSLh7/atKMB+56UwwU+8MbJXYQ8jNvqtd1DgoNc0m8CAwEAAQ==

logging:
  config: classpath:log4j2-spring.xml